=== milendd/xslt_parser/test/samples/BattleCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.somewhere.org/BattleCatalog" targetNamespace="http://www.somewhere.org/BattleCatalog" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:simpleType name="EraType" final="restriction">
        <xs:annotation>
            <xs:documentation>Епоха</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Античност"/>
            <xs:enumeration value="Средновековие"/>
            <xs:enumeration value="Ренесанс"/>
            <xs:enumeration value="Ново време"/>
            <xs:enumeration value="Съвременна епоха"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ConflictType" final="restriction">
        <xs:annotation>
            <xs:documentation>Вид на конфликта</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Битка"/>
            <xs:enumeration value="Война"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ParticipantType">
        <xs:annotation>
            <xs:documentation>Данни за воюващата страна</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Наименование</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Army" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Силите с които участва страната в конфликта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Losses" type="xs:string" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Резултат от конфликта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Commanders" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Командири</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Commander">
                            <xs:annotation>
                                <xs:documentation>Командир</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:attribute name="Name">
                                    <xs:annotation>
                                        <xs:documentation>Имена на командир</xs:documentation>
                                    </xs:annotation>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="BattleType">
        <xs:annotation>
            <xs:documentation>Данни за конфликта</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Наименование</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="StartDate" type="xs:date" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>Начална дата</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="EndDate" type="xs:date" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>Крайна дата</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Place" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Местоположение</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Era" type="ns1:EraType" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Епоха</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Reason" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Причина или повод</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="ConflictType" type="ns1:ConflictType">
                <xs:annotation>
                    <xs:documentation>Тип на конфликта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Attackers">
                <xs:annotation>
                    <xs:documentation>Атакуващи сили</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Attacker" type="ns1:ParticipantType">
                            <xs:annotation>
                                <xs:documentation>Атакуващ</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="TotalArmy" use="required"/>
                    <xs:attribute name="TotalLosses" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Defenders">
                <xs:annotation>
                    <xs:documentation>Защитни сили</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Defender" type="ns1:ParticipantType">
                            <xs:annotation>
                                <xs:documentation>Защитник</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="TotalArmy" use="required"/>
                    <xs:attribute name="TotalLosses" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Result" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Резултат от конфликта</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="BattleCatalog">
        <xs:annotation>
            <xs:documentation>Каталог с битки</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Battle" type="ns1:BattleType" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Информация за битка</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== milendd/xslt_parser/test/samples/BattleCatalog.xml
<?xml version="1.0"?>
<BattleCatalog xmlns="http://www.somewhere.org/BattleCatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.somewhere.org/BattleCatalog BattleCatalog.xsd">
    <Battle>
        <Name>Руско-турска война</Name>
        <StartDate>1877-04-24</StartDate>
        <EndDate>1878-03-23</EndDate>
        <Place>Източни Балкани(дн. България), Кавказ</Place>
        <Era>Ново време</Era>
        <Reason>Въстанието в Босна и Херцеговина (1875), Априлското въстание в България (1876) и Сръбско-турската война (1876)</Reason>
        <ConflictType>Война</ConflictType>
        <Attackers TotalArmy="440000" TotalLosses="24000">
            <Attacker>
                <Name>Русия</Name>
                <Army>185000 в Румъния и 100000 в Кавказ</Army>
                <Losses>15567 убити, 56652 ранени</Losses>
                <Commanders>
                    <Commander Name="император Александър II"/>
                    <Commander Name="княз Николай Николаевич"/>
                    <Commander Name="княз Михаил Николаевич"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>румънци</Name>
                <Army>60000</Army>
                <Losses>7618 убити, ранени, починали и изчезнали</Losses>
                <Commanders>
                    <Commander Name="крал Карол I"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>сърби</Name>
                <Army>56000</Army>
                <Losses>718 убити, 1 534 починали от рани и болести, 2 999 ранени</Losses>
                <Commanders>
                    <Commander Name="крал Милан I"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>черногорци</Name>
                <Army>30000</Army>
                <Losses>Неизвестен брой</Losses>
                <Commanders>
                    <Commander Name="княз Никола I"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>българи</Name>
                <Army>7 500 в Българското опълчение и значителен брой доброволци</Army>
                <Losses>1 347 души от Българското опълчение, значителни загуби сред цивилното население</Losses>
            </Attacker>
        </Attackers>
        <Defenders TotalArmy="281000" TotalLosses="120000 убити">
            <Defender>
                <Name>Османска империя(дн. Турция)</Name>
                <Army>281000 на Балканския и на Кавказкия фронт</Army>
                <Losses>229 838 убити, починали, изчезнали и ранени</Losses>
                <Commanders>
                    <Commander Name="султан Абдул Хамид II"/>
                    <Commander Name="Абдул Керим Надир паша"/>
                    <Commander Name="Ахмед Мухтар паша"/>
                </Commanders>
            </Defender>
        </Defenders>
        <Result>Победа за Руската империя. Териториална подялба на османски владения между Великите сили. Карс и Южна Бесарабия стават част от Руската империя. Възстановяване на българската държавност чрез създаване на васално Княжество България. Признаване на независимостта на васалните дотогава княжества Румъния, Сърбия и Черна гора.</Result>
    </Battle>
    <Battle>
        <Name>Битката при Адрианопол(Одрин)</Name>
        <StartDate>1205-04-14</StartDate>
        <EndDate>1205-04-14</EndDate>
        <Place>Адрианопол(Одрин)</Place>
        <Era>Средновековие</Era>
        <Reason>Латинците от IV-ия кръстоносен поход след установяването си в Константинопол предявяват териториални претенции към българските земи и започват да подлагат на грабеж българските селища</Reason>
        <ConflictType>Битка</ConflictType>
        <Attackers TotalArmy="около 54000" TotalLosses="Неизвестен брой">
            <Attacker>
                <Name>Второ българско царство(дн. България)</Name>
                <Army>Около 40 хиляди българи(пехота, стрелци и конница) и около 14 хиляди кумани(лека конница и конни стрелци)</Army>
                <Losses>Неизвестен брой</Losses>
                <Commanders>
                    <Commander Name="цар Калоян"/>
                </Commanders>
            </Attacker>
        </Attackers>
        <Defenders TotalArmy="между 2 и 4 хиляди души" TotalLosses="220-280 рицари и неизвестен брой войници">
            <Defender>
                <Name>Латинска империя</Name>
                <Losses>Неизвестен брой войници</Losses>
                <Commanders>
                    <Commander Name="император Балдуин I"/>
                </Commanders>
            </Defender>
            <Defender>
                <Name>Венецианска република</Name>
                <Losses>Неизвестен брой войници</Losses>
                <Commanders>
                    <Commander Name="граф Луи дьо Блоа"/>
                    <Commander Name="дож Енрико Дандоло"/>
                </Commanders>
            </Defender>
        </Defenders>
        <Result>Победа за българите</Result>
    </Battle>
    <Battle>
        <Name>Десант в Нормандия</Name>
        <StartDate>1944-06-06</StartDate>
        <EndDate>1944-07-15</EndDate>
        <Place>Нормандия, Северозападна Франция</Place>
        <Era>Съвременна епоха</Era>
        <Reason>Отваряне на втори фронт в Европа и освобождаване на Франция</Reason>
        <ConflictType>Битка</ConflictType>
        
        <Attackers TotalArmy="1332000" TotalLosses="120000">
            <Attacker>
                <Name>САЩ</Name>
                <Army>Неизвестен брой</Army>
                <Losses>Неизвестен брой</Losses>
                <Commanders>
                    <Commander Name="Дуайт Айзенхауер"/>
                    <Commander Name="Омар Брадли"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>Великобритания</Name>
                <Army>Неизвестен брой</Army>
                <Losses>Неизвестен брой</Losses>
                <Commanders>
                    <Commander Name="Артър Тедър"/>
                    <Commander Name="Бернард Монтгомъри"/>
                    <Commander Name="Трафърд Лей-Малори"/>
                    <Commander Name="Бертрам Рамзи"/>
                    <Commander Name="Майлс Дъмпси"/>
                </Commanders>
            </Attacker>
        </Attackers>
            
        <Defenders TotalArmy="380000" TotalLosses="113059">
            <Defender>
                <Name>Нацистка Германия</Name>
                <Army>380000</Army>
                <Losses>113059</Losses>
                <Commanders>
                    <Commander Name="Герд фон Рундщед"/>
                    <Commander Name="Ъруин Ромел"/>
                    <Commander Name="Фридрих Долман"/>
                    <Commander Name="Лео Гейр фон Швепенбърг"/>
                </Commanders>
            </Defender>
        </Defenders>
            
        <Result>Успешно приземяване на съюзническите войски и изтласкване на немската армия в посока Париж</Result>
    </Battle>
    <Battle>
        <Name>Битка при Сталинград</Name>
        <StartDate>1942-07-17</StartDate>
        <EndDate>1943-02-02</EndDate>
        <Place>Сталинград( днес Волгоград), Русия</Place>
        <Era>Съвременна епоха</Era>
        <Reason>Превземане на петролните залежи край Каспийско море и към стратегически важния център Сталинград</Reason>
        <ConflictType>Битка</ConflictType>
        
        <Attackers TotalArmy="1 011 000 войници, 675 танка, 10 290 оръдия, 1216 самолета" TotalLosses="627 899 войници, 1500 танка, 6000 оръдия, 900 самолета">
            <Attacker>
                <Name>Германия</Name>
                <Army>400 000</Army>
                <Losses>299 899</Losses>
                <Commanders>
                    <Commander Name="Адолф Хитлер"/>
                    <Commander Name="Фридрих фон Паулус"/>
                    <Commander Name="Ерик фон Манщайн"/>
                    <Commander Name="Вон Рихтофен"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>Италия</Name>
                <Army>220 000</Army>
                <Losses>114 000</Losses>
                <Commanders>
                    <Commander Name="Итало Гарибалди"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>Румъния</Name>
                <Army>144 000</Army>
                <Losses>109 000</Losses>
                <Commanders>
                    <Commander Name="Петре Димитреску"/>
                    <Commander Name="К. Константинеску"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>Унгария</Name>
                <Army>200 000</Army>
                <Losses>105 000</Losses>
                <Commanders>
                    <Commander Name="Густав Яни"/>
                </Commanders>
            </Attacker>
            <Attacker>
                <Name>Хърватия</Name>
                <Army>Неизвестен брой</Army>
                <Losses>Неизвестен брой</Losses>
            </Attacker>
        </Attackers>
        
        <Defenders TotalArmy="1 143 000 войници, 894 танка, 13 451 оръдия, 1115 самолета" TotalLosses="">
            <Defender>
                <Name>СССР</Name>
                <Army>1 143 000 войници, 894 танка, 13 451 оръдия, 1115 самолета</Army>
                <Losses>1 129 619 войници, 4341 танка, 15 728 оръдия, 2769 самолета</Losses>
                <Commanders>
                    <Commander Name="Георги Жуков"/>
                    <Commander Name="Николай Воронов"/>
                    <Commander Name="А. М. Василевски"/>
                    <Commander Name="Андрей Йероменко"/>
                    <Commander Name="Никита Хрусчов"/>
                    <Commander Name="К. К. Рокосовски"/>
                    <Commander Name="Николай Ватутин"/>
                    <Commander Name="Василий Чуков"/>
